### ISSUE TITLE
Streaming from camera is not supported in background for iOS

### ISSUE THREAD

**Issue by arpitthinglogix** [aws-samples/amazon-ivs-broadcast-ios-sample#15]
After giving permissions of background modes like - voice for IP , background fetch, audio (I tried all single and together as well). But as soon as app goes in background mode streaming stops automatically. 

is there a way to handle streaming in background for iOS applications ?

**Comment by bclymer** [comment]
Yes there is, please use the [createAppBackgroundImageSource](https://aws.github.io/amazon-ivs-broadcast-docs/1.3.0/ios/Classes/IVSBroadcastSession.html#/c:objc(cs)IVSBroadcastSession(im)createAppBackgroundImageSourceWithAttemptTrim:OnComplete:) API. Apple does not allow GPU access in the background, which means it is not possible to continue to encode live video. This API lets you work around this limitation by continuing to broadcast live audio while looping pre-encoded video.
