### ISSUE TITLE
[Question] Is possible to add features in AVFoundation to AmazonIVSBroadcast?

### ISSUE THREAD

**Issue by yuya-h-29** [aws-samples/amazon-ivs-broadcast-ios-sample#21]
I used the ivs-broadcast-ios-sample and now I'm able to stream to IVS, and currently trying to add features like

- adjust focus & exposure (like using [`focusMode`](https://developer.apple.com/documentation/avfoundation/avcapturedevice/1389191-focusmode)  in AVCaptureDevice )

- enable to take pictures while streaming (like using [`capturePhoto(with:delegate:)`](https://developer.apple.com/documentation/avfoundation/avcapturephotooutput/1648765-capturephoto) )

- zoom in & out (with [`videoZoomFactor`](https://developer.apple.com/documentation/avfoundation/avcapturedevice/1624611-videozoomfactor) )

I tried to add those features by accessing `IVSDevice` and `IVSBroadcastSession` (since I thought it's similar to `AVCaptureDevice` and `AVCaptureSession`, but obviously they don't support any features above.)

How can I add those features using AmazonIVSBroadcast? and is it possible to, for example, add adjusting focus & exposure with ivsBroadcast?

**Comment by bclymer** [comment]
Hi @yuya-h-29 , unfortunately those are not features the IVS Broadcast SDK provides. We may add them sometime in the future, but we have no timeline for those features yet.

I recommend that you manually attach an `AVCaptureSession`, which will give you full control over the camera (including focus, zoom, and taking pictures). We provided sample code of how to do that [here](https://github.com/aws-samples/amazon-ivs-broadcast-ios-sample/blob/c10785e7c3b150e9d162ad27567c7a46a75f550c/BasicBroadcast/ViewControllers/CustomSourcesViewController.swift).

**Comment by yuya-h-29** [comment]
@bclymer 
Thank you so much for the super quick response!!
Looking forward to getting those features added to this SDK!!!
I'm gonna try manually attaching the AVCaptureSession for now, I'll let you know if further support is needed.
Again, thank you so much!!

**Comment by bclymer** [comment]
Sounds good. I'm going to close out this issue for now. [Here](https://docs.aws.amazon.com/ivs/latest/userguide/release-notes.html) is where you can find detailed release notes for our SDK updates.
