### ISSUE TITLE
Camera disappear when switching from background to foreground

### ISSUE THREAD

**Issue by ppth0608** [aws-samples/amazon-ivs-broadcast-ios-sample#24]
hello.

I am currently using version 1.5.2.

There were no bugs when using version 1.4.0, but after version 1.5.2, a bug that the camera disappears intermittently when the app is returned from the background to the foreground during broadcasting.

After the camera disappears, When i change the camera to the front camera or the rear camera, it will be exposed normally.

It also often crashes in the background state.

Is there any solution?
thank you!

**Comment by ppth0608** [comment]
This is crash debug log

<img width="1651" alt="스크린샷 2022-09-19 오후 6 31 59" src="https://user-images.githubusercontent.com/9531750/190989338-2b3cc3d1-db10-4597-b20c-417531c1bb8a.png">

**Comment by bclymer** [comment]
Hey @ppth0608, thanks for the report. That is a scenario we test and we haven't seen issues, but we will investigate it further. 

Could you attach a full crash report here? If you've seen this in production you can export the `.xccrashpoint` file from the Organizer (right click on a crash -> Find in Finder), or if you have a crashing device locally you can export the `.crash` file from the Devices section of Xcode. Either would be very helpful for us resolving this issue for you.

**Comment by ppth0608** [comment]
@bclymer Thank you for reply.

It's not released, so it's hard to figure out the crash log.

But, After some tests, the above issue was reproduced in the following situations:
When using a mixer slot and layout the preview through `IVSBroadcastSession.preview(aspectMode:)`

**Comment by ppth0608** [comment]
In the MixerViewController example of the BasicBroadcast app, the same crash occurs when entering the foreground from the background.

At this time, the error log that occurs is as follows.

> BasicBroadcast[2578:1449883] Execution of the command buffer was aborted due to an error during execution. Insufficient Permission (to submit GPU work from background) (IOAF code 6)

**Comment by bclymer** [comment]
@ppth0608 I have a couple clarifying questions.

1. Are you able to get the BasicBroadcast app to actually crash, or just print the error you provided? I was able to get the error, but never a crash.
2. Are you using a custom image source in your own application?

What's happening in the `MixerViewController` is that image samples are still sent from the custom image source (the video) to the SDK after the app is in the background, and iOS devices restrict GPU access to foreground applications only. The SDK will manage the camera lifecycle and stop sending camera samples when entering the background, but custom image sources that are managed by the host application need to do that themselves (our sample app does not). Eventually Apple won't even process your GPU samples in the foreground without a long enough timeout.

**Comment by bclymer** [comment]
Closing this ticket due to inactivity. Please open a new ticket if you are still experiencing issues.
