### ISSUE TITLE
How to update the video size for IVSBroadcastConfiguration when the device get rotated?

### ISSUE THREAD

**Issue by yuya-h-29** [aws-samples/amazon-ivs-broadcast-ios-sample#29]
Sorry for asking many questions...🙇🏻

Currently, I'm trying to change the video size when the device is rotated. The supported orientation of my app is portrait and landscape left & right. 
Like `#1` and `#2` in the image below,  I can change the video size by setting up the broadcast session from scratch when the device gets rotated. It works ok, but it generates a little lag when the device is rotated, for example, the camera view gets frozen for about one second, and sometimes the preview view (I use `IVSImagePreviewView`) starts shaking until the new broadcast session is applied. I guess the time lag happens since I create and apply a new `broadcastsession` every time when the device gets rotated. So, I'm trying to just update both video sizes for `IVSBroadcastConfiguration` and `IVSMixerSlotConfiguration` instead of setting up the new broadcast session. I get how to update the video size for `IVSMixerSlotConfiguration`, but I'm not sure how to update the size of `IVSBroadcastConfiguration`. If I don't change the video size for the broadcastConfiguration, like the image of `#1` to `#3`, both preview view size and streaming video size are not wide enough to cover the screen.

I've read the documentation for `IVSBroadcastConfiguration` and I understood just changing properties won't update the broadcast configuration after it's provided to `IVSBroadcastSession` and recommended using `IVSBroadcastSession.mixer` APIs. 
But what would be the better way to update the video size for  `IVSBroadcastConfiguration` after its provided to the broadcast session?
(in my case, `CGSize(width: 1080, height: 1920)` to `CGSize(width: 1920, height: 1080)`)

Thank you in advance!

<img width="740" alt="Screen Shot 2022-11-08 at 12 47 48" src="https://user-images.githubusercontent.com/54800510/200470786-6182ebe4-1175-47a9-b786-c2765b9b7f47.png">

My code is something like this. 

    var videoOrientation: AVCaptureVideoOrientation = .portrait
    var broadcastSession: IVSBroadcastSession?
    
     override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        setupIVSBroadcastSession() // <- this is called first
    }

    //  setup broadcastsession everytime when the device is rotated
    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        super.viewWillTransition(to: size, with: coordinator)
        setupIVSBroadcastSession()
    }
    
    func setupIVSBroadcastSession() {
        let videoSize = (videoOrientation == .landscapeLeft) || (videoOrientation == .landscapeRight) ? CGSize(width: 1920, height: 1080) : CGSize(width: 1080, height: 1920)
        
        do {
            IVSBroadcastSession.applicationAudioSessionStrategy = .playAndRecord
            let config = IVSBroadcastConfiguration()
            try config.audio.setBitrate(BroadcastSetting.audioBitrate)
            try config.video.setInitialBitrate(BroadcastSetting.initialBitrate)
            try config.video.setMaxBitrate(BroadcastSetting.maxBitrate)
            try config.video.setTargetFramerate(BroadcastSetting.frameRate)
            try config.video.setSize(videoSize)
            config.video.autoBitrateProfile = .fastIncrease
            config.video.enableTransparency = true
            
            let customSlot = IVSMixerSlotConfiguration()
            customSlot.size = config.video.size
            customSlot.position = CGPoint(x: 0, y: 0)
            customSlot.preferredAudioInput = .userAudio
            customSlot.preferredVideoInput = .userImage
            try customSlot.setName("custom-slot")
            
            config.mixer.slots = [customSlot]

            IVSBroadcastSession.applicationAudioSessionStrategy = .noAction
            let broadcastSession = try IVSBroadcastSession(configuration: config,
                                                           descriptors: nil,
                                                           delegate: self)
            // more setting here...
            
            self.broadcastSession = broadcastSession
        } catch {
            print("error: \(error)")
        }
    }

**Comment by bclymer** [comment]
There is no way to change the resolution of the video while broadcasting, so we do not support changing the resolution locally for an `IVSBroadcastSession` either. However, you should not need to change resolution, just pick whichever resolution works best for your viewer (probably 1920 width x 1080 height). The SDK adds letterboxing to the broadcast based on the orientation of the device (that is what you see in image #3), so the content will always be oriented correctly, but might have black bars. Using Aspect Modes you can remove the black bars (change from FIT to FILL on your slot).

I might be misunderstanding, but the "viewer side" looks correct in both images? Or is that not the desired resolution? 

It also looks like you are using `IVSBroadcastSession.previewView` instead of `IVSImageDevice.previewView`. See [this file](https://github.com/aws-samples/amazon-ivs-broadcast-ios-sample/blob/main/BasicBroadcast/ViewControllers/LiveBroadcastViewController.swift) for how we use the camera to generate a preview, instead of the session itself. That will prevent the extra letterboxing you are seeing.

**Comment by yuya-h-29** [comment]
@bclymer 
As you told me, setting the video width & height to 1920 x 1080 and setting aspect mode to fill solves the problem! 

> I might be misunderstanding, but the "viewer side" looks correct in both images? Or is that not the desired resolution?

-> I forgot to add a comment on this, but the viewer side screens are the desired outcome. I should have added another image to describe what the current viewer side looks like (It didn't fill the enter screen before saving the issue).  

For the `previewView`, I'm using` IVSBroadcastSession.previewView `, since I want to display some images on the stream and want to see the preview locally. But thank you for letting me know!!

Thank you as always!
