### ISSUE TITLE
Remove Participant.

### ISSUE THREAD

**Issue by rishopbabu** [aws-samples/amazon-ivs-broadcast-ios-sample#39]
Hi team,
              Is there any option that the Publisher to remove user from the IVSstages call. And one more thing if the publisher leaves the IVSstages, can we remove all the members in the IVSstages call.  Kindly help me with this team. Thanks In advance.

**Comment by bclymer** [comment]
Hi @rishopbabu, that functionality could be controlled by using the AWS APIs for Stages, but it is not possible through the iOS SDK (this repo).
