### ISSUE TITLE
Camera and Mic Issue.

### ISSUE THREAD

**Issue by rishopbabu** [aws-samples/amazon-ivs-broadcast-ios-sample#40]
Hi team,
             I'm facing an issue like, after I leave the stage and even deleted the stage, camera and mic is still running in the background. Does it work like this or this has any solution. Thanks in Advance.

**Comment by rishopbabu** [comment]
self.broadcastSession?.stop()
self.broadcastSession = nil
self.deleteStage(stageArn: self.stageArnValue) #(API calling)

this is what I do when leave the delete the stage.

**Comment by bclymer** [comment]
Hi @rishopbabu , the camera and microphone are devices that exist outside of a Stage and Broadcast, but can be attached to them. This means when you leave the stage and stop the broadcast, the device still exists and is running. 

You need to set all your local references to the device to `nil`, including any `IVSLocalStageStream` references. The devices might also still be attached to the Stage and BroadcastSession even if you've cleared your own references. You could fix this by setting those to `nil` as well (I see you already do that for BroadcastSession), or by detaching the devices.

You can use the Xcode memory debugger to look for these objects to see what is holding a reference to them as well. `IVSCameraSource` and `IVSMicrophoneSource` are the class names for the camera and microphone devices.

**Comment by rishopbabu** [comment]
Hi @bclymer, I'm facing an issue while implementing stages. Can you please help me with this. I'd really appreciate it.
When a publisher joins the stage first, then the subscriber joins next, the collection view is updating for the subscriber, but now for the publisher. `	public func participantUpdates() {
		
		viewModel.participantUpdates.add { [weak collectionView] (index, changeType, participant) in
			// UICollectionView automatically clears itself out when it gets detached from it's
			// superview it seems (which for us happens when the VC is dismissed).
			// So even though our update/insert/reload calls are in sync, the UICollectionView
			// thinks it has 0 items if this is invoked async after the VC is dismissed.
			guard collectionView?.subviews != nil else { return }
			switch changeType {
			case .inserted:
				collectionView?.insertItems(at: [IndexPath(item: index, section: 0)])
			case .updated:
				// Instead of doing reloadItems, just grab the cell and update it ourselves. It saves a create/destroy of a cell
				// and more importantly fixes some UI glitches. We don't support scrolling at all so the index path per cell
				// never changes.
				guard let participant = participant else { return }
				if let cell = collectionView?.cellForItem(at: IndexPath(item: index, section: 0)) as? ParticipantCollectionViewCell {
					cell.set(participant: participant)
				}
			case .deleted:
				collectionView?.deleteItems(at: [IndexPath(item: index, section: 0)])
			}
		}
	}` 

I called this function inside the viewdidload().
