### ISSUE TITLE
is there any way to differentiate?

### ISSUE THREAD

**Issue by rishopbabu** [aws-samples/amazon-ivs-broadcast-ios-sample#41]
Hi team, 
             Is there any way to list the users inside the stage? I can't find any. Can you please help me I really appreciate. Thanks in advance

**Comment by bclymer** [comment]
There is no API that directly returns all participants in a Stage. By observing `IVSStageRenderer`'s `participantDidJoin` and `participantDidLeave` delegates, you can maintain a list of the current participants. If you join a Stage that already has 5 participants, `participantDidJoin` will be called 5 times shortly after you join, so the list should always be accurate.

**Comment by rishopbabu** [comment]
Thanks for your support @bclymer.
