### ISSUE TITLE
Video quality issue with Basic Portrait feature for iOS 16.4.1 users

### ISSUE THREAD

**Issue by cemnisan** [aws-samples/amazon-ivs-broadcast-ios-sample#42]
Hello,

We have noticed a significant drop in video quality when using the Basic Portrait feature to broadcast with the Amazon-IVS-Broadcast library on iOS 16.4.1. We would like to open an issue to address this problem.

The issue is as follows: when users with iOS 16.4.1 installed use the Basic Portrait feature to broadcast, the video quality drops drastically to the point where it becomes unwatchable. However, users who do not have iOS 16.4.1 installed are able to broadcast using the Basic Portrait feature and achieve good video quality.

If you have any insights into the cause and solution for this problem, please let us know. We will do our best to investigate and find a solution.

Thank you.

**Comment by bclymer** [comment]
Hey @cemnisan, unfortunately there was a bug in iOS 16.4.x causing this. There are 2 workarounds for now

1. Enable B-frames in your video configuration. 
2. Upgrade to iOS 16.5 Beta 3+

Thankfully Apple fixed the issue rather quickly, but it does leave us with the unfortunate situation of having iOS 16.4 be a problem OS version when B-frames are disabled.

**Comment by cemnisan** [comment]
Hello @bclymer, 

Thank you for your response.

For iOS 16.4.1, enable usesBFrames worked. We will use this feature only  for iOS 16.4.1 users. Thank you for your support.
