### ISSUE TITLE
Streaming issue in IVSBroadcaster.

### ISSUE THREAD

**Issue by rishopbabu** [aws-samples/amazon-ivs-broadcast-ios-sample#43]
Hi @bclymer,
          While testing in test server the broadcast streams good. But when I push the stream to production I'm getting an error like this. Can you please help me with this. I really appreciate it. Thanks in advance. 

Error (Code: 20105)
Source: StartBroadcast
Error: URI contains an invalid scheme (rtmp://11.11.11.111:1111/live)

Need some add on informations.
- where can we find the error document. 
- where to turn off the logs.

**Comment by bclymer** [comment]
Streaming with our SDK requires `rtmps://`, we do not accept `rtmp://` for security reasons.
