### ISSUE TITLE
User status not updated properly in negative scenario.

### ISSUE THREAD

**Issue by rishopbabu** [aws-samples/amazon-ivs-broadcast-ios-sample#47]
Hi @bclymer,
 we are facing one scenario, like if  one user in the stage is goes offline or mobile switched off. At that time the user reflects in stage. How can we get the proper status? Kindly suggest to handle this. Thanks in advance.

**Comment by rishopbabu** [comment]
Should we call requestRTCStats inside the participant collection cell or view model file? Can you please help me with this. Thanks in advance.

**Comment by bclymer** [comment]
I can't provide a recommendation on that, as that is about your app's architecture and not our SDK. Please do whatever fits best with your app.
