### ISSUE TITLE
Camera view is Black..!!

### ISSUE THREAD

**Issue by rishopbabu** [aws-samples/amazon-ivs-broadcast-ios-sample#49]
Sometimes the camera view is black screen, but the black feed is streaming and audio is also audible. Team can you help me with this. Thanks in advance.

**Comment by rishopbabu** [comment]
- iOS version: 16.4
- iOS devide: iPhoneSE, iPhone11 - these devices we tested on so far.
- StageViewModel -> used the same as the sample GitHub project.

And when I destroy the session I make this object to nil "StageViewModel"

**Comment by bclymer** [comment]
When you set `StageViewModel` to `nil` you are tearing down the object that owns the camera, you need to keep a reference to the camera for it to keep working.

**Comment by rishopbabu** [comment]
Hi @bclymer, in our application we used to go live once in a while, So only we set **StageViewModel** to nil. When I go next live only we initiate the **StageViewModel** again. If I keep a reference, the app memory will affect and also camera view will be In the background(shows a privacy note in control centre). To over come this only we used to nil the **StageViewModel**. Is there any alternate solution?

**Comment by bclymer** [comment]
If you are setting `StageViewModel` to `nil`, you will need to create a new camera preview with your new `StageViewModel` and attach that to the UI. You can't use the old camera preview if the `StageViewModel` that owned the camera is gone.

**Comment by rishopbabu** [comment]
Thanks for your help, really appreciate @bclymer
