### ISSUE TITLE
Stream image sometimes gets distorted. 

### ISSUE THREAD

**Issue by yuya-h-29** [aws-samples/amazon-ivs-broadcast-ios-sample#61]
@bclymer 

Hello, I wanted to check if the following issue has already been reported.

I'm using `AmazonIVSBroadcast 1.9.0` in production and `1.12.0` in development. In both environments, there is sometimes image distortion or fuzziness when moving the camera slightly during streaming. I've attached example videos in a [Google Drive](https://drive.google.com/drive/folders/1Xr4kakYKnr8papHZ8itsgx3gX_hqUDgU?usp=sharing).
The drive contains two folders - `No Issue` and `With Issue`. Each folder has a local video record and a screen capture of the IVS console.

As you can see in the `With Issue` video `camera_issue_console.mov`, when I move the device while streaming, the video seems disturbed, with image frames remaining frozen in a short while. The local record `camera_issue_local.mp4` shows how I moved the camera during streaming. Here is a screenshot of the bitrate and FPS during the distorted stream, though conditions seemed ok:

<img width="763" alt="cameraissue" src="https://github.com/aws-samples/amazon-ivs-broadcast-ios-sample/assets/54800510/31131ed7-b431-48a9-9424-cbb5fa481e94">

---

This issue does not always occur. As shown in the `No Issue` folder, some streams under similar conditions have smooth video.
Let me know if this helps explain the problem! I'd appreciate any advice if this is a known issue and workaround.

---

My app
- streams from iPhone using wifi
- allows local record and save the video to the photo library
- max bitrate setting　→　6,500 kbps
- initial bitrate setting　→　3,000 kbps
- video autoBitrateProfile setting　→　fast increase

**Comment by bclymer** [comment]
Hey @yuya-h-29, thank you for the detailed issue plus examples, that was very helpful!

Could you try setting `usesBFrames` in your `IVSVideoConfiguration` to `false`? 
https://aws.github.io/amazon-ivs-broadcast-docs/1.12.0/ios/Classes/IVSVideoConfiguration.html#/c:objc(cs)IVSVideoConfiguration(py)usesBFrames

We have received a few reports recently of b-frames causing issues like that.

**Comment by yuya-h-29** [comment]
Hi @bclymer !
I changed the useBFrames property to false and confirmed this solved the issue. Thank you so much for your help with this!

**Comment by yuya-h-29** [comment]
@bclymer 
Thank you so much for the suggestion!! When you mentioned you've received a few similar reports recently, could you clarify what general timeframe you meant by 'recently'? I want to get a sense of when this problem started coming up for others as well. 
Please let me know if there are any other details that would be helpful!

**Comment by bclymer** [comment]
Hi @yuya-h-29 . We believe this issues started around Oct 1 due to a backend change. The issue should be fixed for all configurations of the SDK now (b-frames can be enabled or disabled). But disabling b-frames was a workaround while the server-side issue existed.

**Comment by yuya-h-29** [comment]
@bclymer Thank you for the quick and detailed explanation:) 
 I understand now the backend issue has been resolved and no longer need to manually disable b-frames as a workaround. Thanks again for the helpful support!
