### ISSUE TITLE
An error occurred while installing json (2.6.1), and Bundler cannot continue.

### ISSUE THREAD

**Issue by RupamShaw** [aws-samples/amazon-ivs-broadcast-ios-sample#7]
on bundle install it gives
An error occurred while installing json (2.6.1), and Bundler cannot continue.
tried with latest ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
In Gemfile:
  cocoapods was resolved to 1.11.2, which depends on
    cocoapods-core was resolved to 1.11.2, which depends on
      algoliasearch was resolved to 1.27.5, which depends on
        json

**Comment by RupamShaw** [comment]
resolved by https://github.com/CocoaPods/CocoaPods/issues/10286
curl -sSL https://get.rvm.io | bash -s stable
close and reopen terminal
rvm install ruby@latest
rvm use ruby-3.0.0 --default

**Comment by nawfalhaddi** [comment]
I've solved it by installing Command Line Tools Xcode of the version I have. I hope this help someone else.
